defaults/xdg/lliurex/desktop	/etc/xdg/lliurex
defaults/profile.d/* /etc/profile.d/
defaults/skel/.[a-zA-Z0-9]*			/etc/skel/
defaults/searchproviders/* /usr/share/kservices5/searchproviders/
bin/*	/usr/bin/
defaults/dconf/lliurex	/etc/dconf/profile/
defaults/dconf/01_desktop_settings	/etc/dconf/db/lliurex.d/
avatars/*.png	/usr/share/plasma/avatars/lliurex/
locale/mos/* /usr/share/locale/
plasmoids/*	/usr/share/plasma/plasmoids/
wallpapers/net.lliurex.wallpaper /usr/share/plasma/wallpapers/

